#!/bin/sh

if [ "x$9" = "x" ]
then
	echo "Usage: generate-mobileconfig <pkcs12file> <pkcs12pwd> <name> <ufqdn> <ondemand/normal> <server hostname> <sfqdn> <domain> <dns> [File UUID]"
	exit 1
fi

uuid1=$(uuidgen)
uuid2=$(uuidgen)
uuid3=$(uuidgen)

pkcs12filename=$1
pkcs12pwd=$2
pkcs12base=$(basename "$pkcs12filename")
name=$3
ufqdn=$4
template=$5
server=$6
sfqdn=$7
domain=$8
dns=$9

if [ ! -f "$(dirname "$0")/${template}.tmpl" ]
then
	echo "Template not found"
	exit 1
fi

if [ ! -f "$pkcs12filename" ]
then
	echo "Certificate file not found"
	exit 1
fi

if [ "x${10}" = "x" ]
then
      uuidname=$(uuidgen)
else
	uuidname="${10}"
fi

pkcs12data=$(openssl enc -base64 < "$pkcs12filename" | tr -d '\n')

cat "$(dirname "$0")/${template}.tmpl" | sed -e "s|##pkcs12data##|$pkcs12data|g" | sed -e "s|##pkcs12filename##|$pkcs12base|g" | sed -e "s|##password##|$pkcs12pwd|g" | sed -e "s|##uuid1##|$uuid1|g" | sed -e "s|##uuid2##|$uuid2|g" | sed -e "s|##uuid3##|$uuid3|g" | sed -e "s|##uuidname##|$uuidname|g" | sed -e "s|##name##|$name|g" | sed -e "s|##ufqdn##|$ufqdn|g" | sed -e "s|##sfqdn##|$sfqdn|g" | sed -e "s|##name##|$name|g" | sed -e "s|##domain##|$domain|g" | sed -e "s|##server##|$server|g" | sed -e "s|##dns##|$dns|g"  > "$name.$uuidname.mobileconfig"
